// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.9.21'

    ext.configuration = [
            applicationId       : "org.qstuff.qdeq",
            compileSdkVersion   : 34,
            buildToolsVersion   : "33.0.1",
            minSdkVersion       : 24,
            targetSdkVersion    : 34,
            versionCode         : 300,
            versionName         : "3.0.0",
            versionCommitCount  : 300 + "git rev-list HEAD --count".execute([], project.rootDir).text.trim().toInteger()
    ]

    ext.libs = [
            appcompat               : '1.4.2',
            constraintLayout        : '2.1.4',
            coroutines              : '1.7.2',
            crashlytics             : '18.6.2',
            espresso                : '3.4.0',
            espressoRunner          : '1.4.0',
            firebase                : '21.1.1',
            gson                    : '2.10.1',
            jUnit                   : '4.13.2',
            koin                    : '3.5.3',
            ktx                     : '1.12.0',
            lifecycle               : '2.7.0',
            material                : '1.11.0',
            multidex                : '1.0.3',
            preference              : '1.2.1',
            room                    : '2.6.1',
            timber                  : '5.0.1',
        media3                  : '1.4.1',
    ]

    repositories {

        mavenCentral()
        google()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://jitpack.io' }
    }

    dependencies {

        classpath 'com.google.gms:google-services:4.4.1'
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://jitpack.io' }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
