// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.6.10'

    ext.configuration = [
            applicationId       : "org.qstuff.qplayer",
            compileSdkVersion   : 31,
            buildToolsVersion   : "30.0.2",
            minSdkVersion       : 24,
            targetSdkVersion    : 31,
            versionCode         : 220,
            versionName         : "2.2.0",
            versionCommitCount  : 220 + "git rev-list HEAD --count".execute([], project.rootDir).text.trim().toInteger()
    ]

    ext.libs = [
            appcompat               : '1.4.2',
            constraintLayout        : '2.1.4',
            coroutines              : '1.6.1',
            crashlytics             : '18.2.11',
            espresso                : '3.4.0',
            espressoRunner          : '1.4.0',
            firebase                : '21.0.0',
            gson                    : '2.8.9',
            jUnit                   : '4.13.2',
            koin                    : '1.0.2',
            ktx                     : '1.8.0',
            lifecycle               : '2.2.0',
            material                : '1.6.1',
            multidex                : '1.0.3',
            preference              : '1.2.0',
            room                    : '2.4.2',
            timber                  : '5.0.1',
    ]

    repositories {

        mavenCentral()
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://jitpack.io' }
    }

    dependencies {

        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.android.tools.build:gradle:7.0.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://jitpack.io' }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
