apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())

// path to the superpowered SDK
def superpowered_sdk_path = properties.getProperty('superpowered.dir')

// defs from the root level build.gradle
def cfg  = rootProject.ext.configuration
def libs = rootProject.ext.libs

android {
    compileSdkVersion cfg.compileSdkVersion
    buildToolsVersion cfg.buildToolsVersion

    defaultConfig {
        applicationId cfg.applicationId

        minSdkVersion cfg.minSdkVersion
        targetSdkVersion cfg.targetSdkVersion
        versionCode cfg.versionCommitCount
        versionName cfg.versionName

        vectorDrawables.useSupportLibrary = true

        testInstrumentationRunner 'android.support.test.runner.AndroidJUnitRunner'

        externalNativeBuild {
            System.out.println("==============")

            cmake {
                arguments   '-DANDROID_PLATFORM=android-19',
                            '-DANDROID_TOOLCHAIN=clang',
                            '-DANDROID_ARM_NEON=TRUE',
                            '-DANDROID_STL=c++_shared',
                            "-DPATH_TO_SUPERPOWERED:STRING=${superpowered_sdk_path}"

                cFlags '-O3', '-fsigned-char' // full optimization, char data type is signed
                cppFlags '-fsigned-char', "-I${superpowered_sdk_path}"
            }
        }
    }

    android {
        lintOptions {
            abortOnError false
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jni']
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
        }
    }

    buildTypes {

        debug {
           // applicationIdSuffix '.dev'
           // versionNameSuffix "-dev"

            signingConfig android.signingConfigs.debug;
        }

        beta {
           // applicationIdSuffix '.beta'
           // versionNameSuffix "-beta"

            signingConfig android.signingConfigs.debug;

            minifyEnabled true
            debuggable true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled false
            debuggable false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$libs.coroutines"

    implementation "com.google.android.material:material:$libs.material"

    implementation "androidx.core:core-ktx:$libs.ktx"
    implementation "androidx.appcompat:appcompat:$libs.appcompat"
    implementation "androidx.constraintlayout:constraintlayout:$libs.constraintLayout"
    implementation "androidx.lifecycle:lifecycle-extensions:$libs.lifecycle"

    implementation "androidx.room:room-runtime:$libs.room"
    kapt "androidx.room:room-compiler:$libs.room"
    implementation "androidx.room:room-ktx:$libs.room"

    // Koin module injection
    implementation "org.koin:koin-android:$libs.koin"
    implementation "org.koin:koin-androidx-scope:$libs.koin"

    // Logging
    implementation "com.jakewharton.timber:timber:$libs.timber"

    // Crash reporting
    implementation "com.crashlytics.sdk.android:crashlytics:$libs.crashlytics"
    debugImplementation "com.amitshekhar.android:debug-db:$libs.debugDatabase"

    testImplementation "junit:junit:$libs.jUnit"
    androidTestImplementation "androidx.test:runner:$libs.espressoRunner"
    androidTestImplementation "androidx.test.espresso:espresso-core:$libs.espresso"

    implementation project(':HGDialV2-release')
}
apply plugin: 'com.google.gms.google-services'